// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQgMIUMsDfY_V8Awlyx2_Hdnl8Z-8vH7s',
    appId: '1:52616262557:web:6a87cf24d8d94b012af574',
    messagingSenderId: '52616262557',
    projectId: 'flutter-portfolio-project',
    authDomain: 'flutter-portfolio-project.firebaseapp.com',
    storageBucket: 'flutter-portfolio-project.firebasestorage.app',
    measurementId: 'G-8GJFK12WG4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdQEwPwCMqck2i2NobW4g4ynDJwlEkAK8',
    appId: '1:52616262557:android:0847a1f3f6f745462af574',
    messagingSenderId: '52616262557',
    projectId: 'flutter-portfolio-project',
    storageBucket: 'flutter-portfolio-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDv8Dr00ntq6nCqU6np0PBYtQ23-wvMLTc',
    appId: '1:52616262557:ios:692ab3c6bf96b1462af574',
    messagingSenderId: '52616262557',
    projectId: 'flutter-portfolio-project',
    storageBucket: 'flutter-portfolio-project.firebasestorage.app',
    iosBundleId: 'com.example.portfolioProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDv8Dr00ntq6nCqU6np0PBYtQ23-wvMLTc',
    appId: '1:52616262557:ios:692ab3c6bf96b1462af574',
    messagingSenderId: '52616262557',
    projectId: 'flutter-portfolio-project',
    storageBucket: 'flutter-portfolio-project.firebasestorage.app',
    iosBundleId: 'com.example.portfolioProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQgMIUMsDfY_V8Awlyx2_Hdnl8Z-8vH7s',
    appId: '1:52616262557:web:6eae12ed1510310f2af574',
    messagingSenderId: '52616262557',
    projectId: 'flutter-portfolio-project',
    authDomain: 'flutter-portfolio-project.firebaseapp.com',
    storageBucket: 'flutter-portfolio-project.firebasestorage.app',
    measurementId: 'G-3YW4YEHGSV',
  );
}
